import { defineCollection, defineContentConfig, z } from '@nuxt/content'

export default defineContentConfig({
  collections: {
    faktenchecks: defineCollection({
      type: 'page',
      source: 'faktenchecks/**/*.md',
      schema: z.object({
        date: z.date(),
        title: z.string(),
        subtitle: z.string(),
        description: z.string().optional(),
        publishedOn: z.date().or(z.null()),
        verdict: z.enum(['false', 'misleading', 'complex', 'true']).optional(),
        tags: z.set(z.string()),
        authors: z.array(z.string()).optional(),
        claim: z.string().optional(),
        claimAuthor: z.string().optional(),
        claimAppearance: z.string().optional(),
        summary: z.string().optional(),
        keyEvidence: z.array(z.string()).optional(),
        primarySources: z.array(z.object({
          label: z.string(),
          code: z.string().optional(),
          url: z.string().url().optional(),
        })).optional(),
        referenceCodes: z.array(z.string()).optional(),
        quoteCodes: z.array(z.string()).optional(),
      }).strict(),
    }),
    lagerfeuer: defineCollection({
      type: 'page',
      source: 'lagerfeuer/**/*.md',
      schema: z.object({
        date: z.date(),
        title: z.string(),
        subtitle: z.string(),
        description: z.string().optional(),
        publishedOn: z.date().or(z.null()),
        tags: z.set(z.string()),
        authors: z.array(z.string()).optional(),
        referenceCodes: z.array(z.string()).optional(),
        quoteCodes: z.array(z.string()).optional(),
        icon: z.string().optional(),
        iconTxt: z.string().optional(),
        part: z.number().optional(),
      }).strict(),
    }),
    glossar: defineCollection({
      type: 'page',
      source: 'glossar/**/*.md',
      schema: z.object({
        date: z.date(),
        title: z.string(),
        subject: z.string(),
        description: z.string().optional(),
        publishedOn: z.date().or(z.null()),
        tags: z.set(z.string()),
        authors: z.array(z.string()).optional(),
      }).strict(),
    }),
    zitate: defineCollection({
      type: 'page',
      source: 'quellen/*/*/zitate/*.md',
      schema: z.object({
        date: z.date(),
        code: z.string(),
        title: z.string(),
        publishedOn: z.date().or(z.null()),
        tags: z.set(z.string()),
        teaser: z.string(),
        referenceCodes: z.array(z.string()).optional(),
        quoteCodes: z.array(z.string()).optional(),
      }).strict(),
      indexes: [
        { columns: ['code'], unique: true },
      ],
    }),
    quellen: defineCollection({
      type: 'page',
      source: 'quellen/*/*/*.md',
      schema: z.object({
        date: z.date(),
        lastScanned: z.date(),
        name: z.string(),
        description: z.string(),
        publishedOn: z.date().or(z.null()),
        imageAuthor: z.string().or(z.null()).optional(),
        tags: z.set(z.string()),
        sameAs: z.array(z.string()).optional(),
        jobTitle: z.string().optional(),
        affiliation: z.string().optional(),
        referenceCodes: z.array(z.string()).optional(),
        quoteCodes: z.array(z.string()).optional(),
      }).strict(),
    }),
    news: defineCollection({
      type: 'page',
      source: 'news/**/*.md',
      schema: z.object({
        date: z.date(),
        title: z.string(),
        teaser: z.string().optional(),
        publishedOn: z.date().or(z.null()),
      }).strict(),
    }),
    themen: defineCollection({
      type: 'page',
      source: 'themen/*.md',
      schema: z.object({
        date: z.date(),
        title: z.string(),
        subtitle: z.string(),
        description: z.string(),
        intro: z.string(),
        publishedOn: z.date().or(z.null()),
        tags: z.set(z.string()),
        matchTags: z.object({
          any: z.array(z.string()),
          all: z.array(z.string()).optional(),
          exclude: z.array(z.string()).optional(),
        }),
        featured: z.object({
          faktenchecks: z.array(z.string()).optional(),
          lagerfeuer: z.array(z.string()).optional(),
          glossar: z.array(z.string()).optional(),
          quellenlinks: z.array(z.string()).optional(),
          zitate: z.array(z.string()).optional(),
          quellen: z.array(z.string()).optional(),
        }).optional(),
        questions: z.array(z.object({
          question: z.string(),
          answer: z.string(),
        })),
      }).strict(),
    }),
    quellenlinks: defineCollection({
      type: 'page',
      source: 'quellen/*/*/links/**/*.md',
      schema: z.object({
        date: z.date(),
        lastScanned: z.date(),
        sourceDate: z.date(),
        code: z.string(),
        title: z.string(),
        description: z.string().optional(),
        publishedOn: z.date(),
        uri: z.string(),
        type: z.string(),
        verdict: z.enum(['false', 'misleading', 'complex', 'true']).optional(),
        claim: z.string().optional(),
        claimAuthor: z.string().optional(),
        tags: z.set(z.string()),
        coSources: z.set(z.string()),
        referenceCodes: z.array(z.string()).optional(),
        quoteCodes: z.array(z.string()).optional(),
        status: z.array(z.string()).optional(),
      }).strict(),
      indexes: [
        { columns: ['code'], unique: true },
      ],
    }),
  },
})
