const redirects: Record<string, string> = {
  '/quellen/allgemein/bluesky-divers': '/quellen/allgemein/bluesky',
  '/quellen/allgemein/facebook-divers': '/quellen/allgemein/facebook',
  '/quellen/allgemein/tiktok-divers': '/quellen/allgemein/tiktok',
  '/quellen/allgemein/x-divers': '/quellen/allgemein/x',
  '/faktenchecks/gesellschaft/stadtbild': '/lagerfeuer/perspektiven/2025-12-12.merz-stadtbild',
  '/faktenchecks/gesellschaft/arbeitsmarkt/krise-im-rentensystem': '/lagerfeuer/perspektiven/2026-01-05.krise-im-rentensystem',
  // Google 404s: sonstige
  '/faktenchecks/_vorlage': '/faktenchecks',
  '/faktenchecks/politik/parteien': '/faktenchecks',
  '/quellen/medien/ndr/links': '/quellen/medien/ndr',
  '/quellen/nachrichten/tagesschau/links/quellen/tags/SPD': '/tags/spd',
}

// Mapping source-slug → group für alte URLs ohne group-Segment (/quellen/SOURCE/...)
const sourceGroups: Record<string, string> = {
  '2-millionen-stimmen-gegen-afd': 'allgemein',
  'bluesky': 'allgemein',
  'campact': 'allgemein',
  'facebook': 'allgemein',
  'giessen': 'allgemein',
  'moers-ist-bunt-nicht-braun': 'allgemein',
  'omas-gegen-rechts': 'allgemein',
  'tiktok': 'allgemein',
  'we-are-watching-you': 'allgemein',
  'x': 'allgemein',
  'youtube': 'allgemein',
  'correctiv': 'faktenchecks',
  'volksverpetzer': 'faktenchecks',
  'beck-aktuell': 'medien',
  'berlin-story': 'medien',
  'blackoutthesystem': 'medien',
  'bpk': 'medien',
  'cicero': 'medien',
  'compact': 'medien',
  'democratic-socialism-now': 'medien',
  'der-spiegel': 'medien',
  'die-Zeit': 'medien',
  'discover-san-diego': 'medien',
  'endstation-rechts': 'medien',
  'fakten-gegen-rechts': 'medien',
  'focus': 'medien',
  'geradeausdenker-plauen': 'medien',
  'gute-nacht-oesterreich': 'medien',
  'hawkpodcasts': 'medien',
  'hessenschau': 'medien',
  'in-the-know': 'medien',
  'indymedia': 'medien',
  'instagram-misc': 'medien',
  'labor-on-the-line': 'medien',
  'legal-tribune-online': 'medien',
  'markus-lanz': 'medien',
  'mdr': 'medien',
  'mediendienst-integration': 'medien',
  'monitor': 'medien',
  'ndr': 'medien',
  'nuernberger-nachrichten': 'medien',
  'phoenix': 'medien',
  'quer': 'medien',
  'swr-kultur': 'medien',
  't-online': 'medien',
  'taz': 'medien',
  'the-best-of-san-diego': 'medien',
  'the-history-wizard': 'medien',
  'the-oligarchy-is-here': 'medien',
  'the-rest-is-politics': 'medien',
  'welt': 'medien',
  'women-in-america': 'medien',
  'deutschlandfunk': 'nachrichten',
  'dts-nachrichtenagentur': 'nachrichten',
  'presseportal-de': 'nachrichten',
  'sueddeutsche-zeitung': 'nachrichten',
  'tagesschau': 'nachrichten',
  'aktion-deutschland-hilft': 'ngo',
  'amnesty': 'ngo',
  'frag-den-staat': 'ngo',
  'igmetall': 'ngo',
  'pro-asyl': 'ngo',
  'afd': 'parteien',
  'die-linke': 'parteien',
  'fraktion-die-linke-bundestag': 'parteien',
  'gruene-bayern': 'parteien',
  'spd-rheinland-pfalz': 'parteien',
  'spd-thueringen': 'parteien',
  'anna-connely': 'personen',
  'ashleytheebarroness': 'personen',
  'brian-tyler-cohen': 'personen',
  'chan-jo-jun': 'personen',
  'cheyenne-hunt': 'personen',
  'christoph-sieber': 'personen',
  'der-dara': 'personen',
  'dr-idz': 'personen',
  'erik-turk': 'personen',
  'erika-jordan': 'personen',
  'florian-schroeder': 'personen',
  'godless-gardener': 'personen',
  'harry-sisson': 'personen',
  'helen-webberley': 'personen',
  'its-daniel-brln': 'personen',
  'kim-hunt': 'personen',
  'klarsprech': 'personen',
  'klartext-mit-lilly': 'personen',
  'laura-high': 'personen',
  'marc-brost': 'personen',
  'marc-uwe-kling': 'personen',
  'marcant': 'personen',
  'maurice-hoefgen': 'personen',
  'mercedes-chandler': 'personen',
  'michael-bruck': 'personen',
  'michael-kraske': 'personen',
  'mutmacher': 'personen',
  'oliver-gastronomicus-riek': 'personen',
  'paul-klemm': 'personen',
  'philine-litzmann': 'personen',
  'pullupspastapolitics': 'personen',
  'rumgetrieben': 'personen',
  'sabre-bottleneckloser': 'personen',
  'sally-mcmanus': 'personen',
  'sarah-bosetti': 'personen',
  'sina-reisch': 'personen',
  'skorpi-ya': 'personen',
  'steve-hofstetter': 'personen',
  'the-justice-guy': 'personen',
  'tod-maffin': 'personen',
  'tristan-haerter': 'personen',
  'weichreite': 'personen',
  'who-did-what-now': 'personen',
  'wow-motherhood': 'personen',
  'yung-emil': 'personen',
  'aaron-spielmanns': 'politiker',
  'alice-mann': 'politiker',
  'alice-weidel': 'politiker',
  'andreas-audretsch': 'politiker',
  'andreas-winhart': 'politiker',
  'beatrix-von-storch': 'politiker',
  'clara-bunger': 'politiker',
  'cory-booker': 'politiker',
  'detlef-gurth': 'politiker',
  'dirk-wiese': 'politiker',
  'felix-banaszak': 'politiker',
  'felix-doering': 'politiker',
  'ferat-kocak': 'politiker',
  'franziska-brantner': 'politiker',
  'gregor-gysi': 'politiker',
  'heidi-reichinnek': 'politiker',
  'heiner-garg': 'politiker',
  'jens-maier': 'politiker',
  'kai-borrmann': 'politiker',
  'karoline-otte': 'politiker',
  'lamya-kaddor': 'politiker',
  'lena-kotre': 'politiker',
  'lisa-badum': 'politiker',
  'marcel-hopp': 'politiker',
  'marlene-schoenberger': 'politiker',
  'martin-hebner': 'politiker',
  'maximilian-krah': 'politiker',
  'petr-bystron': 'politiker',
  'rasha-nasr': 'politiker',
  'ricarda-lang': 'politiker',
  'robert-habeck': 'politiker',
  'robin-mesarosch': 'politiker',
  'sebastian-fiedler': 'politiker',
  'taylan-kurt': 'politiker',
  'till-steffen': 'politiker',
  'tim-achtermeyer': 'politiker',
  'tino-chrupalla': 'politiker',
  'toni-schuberl': 'politiker',
  'ulrich-siegmund': 'politiker',
  'chaos-computer-club': 'portale',
  'kontrast-at': 'portale',
  'personalwirtschaft': 'portale',
  'wikipedia': 'portale',
  'auswartiges-amt': 'staatlich',
  'bfa': 'staatlich',
  'bka': 'staatlich',
  'bmas': 'staatlich',
  'bmjv': 'staatlich',
  'bpb': 'staatlich',
  'bundeskanzler-de': 'staatlich',
  'bundestag': 'staatlich',
  'europarl': 'staatlich',
  'european-commission': 'staatlich',
  'gesetze-im-internet': 'staatlich',
  'iab': 'staatlich',
  'integrationsmonitoring-nrw': 'staatlich',
  'landtag-sachsen-anhalt': 'staatlich',
  'lpb-rlp': 'staatlich',
  'verfassungsschutz': 'staatlich',
  'vg-koln': 'staatlich',
  'destatis': 'statistik',
  'statista': 'statistik',
  'charles-mcbryde': 'wissenschaft',
  'dietrich-tranhardt': 'wissenschaft',
  'dr-noc': 'wissenschaft',
  'ernst-kistler': 'wissenschaft',
  'forrest-valkai': 'wissenschaft',
  'gerhard-backer': 'wissenschaft',
  'henrik-kleven': 'wissenschaft',
  'ifo': 'wissenschaft',
  'iw-koeln': 'wissenschaft',
  'jessica-knurick': 'wissenschaft',
  'jochen-pimpertz': 'wissenschaft',
  'mai-thi-nguyen-kim': 'wissenschaft',
  'martin-bujard': 'wissenschaft',
  'martina-sauer': 'wissenschaft',
  'professor-neil': 'wissenschaft',
  'uni-duisburg-essen': 'wissenschaft',
  'volker-quaschning': 'wissenschaft',
}

const knownGroups = new Set([
  'allgemein', 'faktenchecks', 'medien', 'nachrichten', 'ngo',
  'parteien', 'personen', 'politiker', 'portale', 'staatlich', 'statistik', 'wissenschaft',
])

export default defineEventHandler((event) => {
  const url = event.path

  // Exact + prefix matches
  for (const [from, to] of Object.entries(redirects)) {
    if (url === from || url.startsWith(from + '/')) {
      return sendRedirect(event, to + url.slice(from.length), 301)
    }
  }

  // Alte URL-Struktur: /quellen/SOURCE/... ohne group-Segment
  if (url.startsWith('/quellen/')) {
    const parts = url.slice('/quellen/'.length).split('/')
    const second = parts[0]
    if (second && !knownGroups.has(second)) {
      const group = sourceGroups[second]
      if (group) {
        return sendRedirect(event, '/quellen/' + group + '/' + parts.join('/'), 301)
      }
    }
  }
})
